extends: airbnb
env:
  browser: true
rules:
  react/jsx-filename-extension: 0
  no-use-before-define:
    - error
    - nofunc
overrides:
    - files:
        - src/**/*.spec.js
        - src/__test__/setup.js
      env:
        mocha: true
      globals:
        expect: false
      rules:
        prefer-arrow-callback: 0
        func-names: 0
        prefer-template: 0
        no-plusplus: 0
        no-unused-expressions: 0
        import/no-extraneous-dependencies: 0
